#!/usr/bin/env python3
"""
CoChem Setup Phase 5: Academic Output, Offloading, & Finalization
Aggregates Phase 1-4 ephemeral states, enforces strict Pydantic validation 
via the Golden Gatekeeper, generates the canonical citation .bib, 
and produces the foundational `cochem_system_config.json`.
"""

import os
import sys
import json
import logging
from pathlib import Path

# Add current directory to path to ensure we can import CoChem-CORE schemas
sys.path.append(os.path.abspath("."))

try:
    from cochem_registry_manager import RegistryManager
    from cochem_registry_schema import (
        CoChemConfig, HardwareConfig, EnginePaths, 
        SiloConfig, RoutingPolicy, HPCConfig
    )
except ImportError:
    print("FATAL: RegistryManager or Schemas not found. Ensure cochem_registry_manager.py "
          "and cochem_registry_schema.py are in the root directory.")
    sys.exit(1)

# ---------------------------------------------------------
# UI & LOGGING PROTOCOLS
# ---------------------------------------------------------
class Colors:
    OKCYAN = '\033[96m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'

logging.basicConfig(
    filename='Logs/cochem_phase5_finalize.log', 
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - [Phase5] - %(message)s'
)
logger = logging.getLogger("CoChem_Phase5")

def print_status(msg: str, status: str = "info") -> None:
    if status == "success":
        print(f" {Colors.OKGREEN}✅ {msg}{Colors.ENDC}")
    elif status == "warning":
        print(f" {Colors.WARNING}⚠️ {msg}{Colors.ENDC}")
    elif status == "fail":
        print(f" {Colors.FAIL}❌ {msg}{Colors.ENDC}")
    else:
        print(f" {Colors.OKCYAN}➡️ {msg}{Colors.ENDC}")

def write_academic_outputs() -> None:
    """Generates the BibTeX file for the dynamic architecture for academic traceability."""
    print_status("Freezing environments and generating Academic locks...", "info")
    
    os.makedirs("Processed", exist_ok=True)
    bib_path = os.path.join("Processed", "cochem_citations.bib")
    
    bibtex = """@misc{cochem2026,
    author = {Klaassen, Joshua John},
    title = {{CoChem Ecosystem: High-Throughput Quantum Orchestration}},
    year = {2026},
    url = {https://github.com/ProfJJK/CoChem-CORE},
    note = {Generated by CoChem Setup Phase 5}
}"""
    try:
        with open(bib_path, "w") as f:
            f.write(bibtex)
        print_status(f"Academic provenance locked to {bib_path}", "success")
        logger.info("cochem_citations.bib successfully generated.")
    except Exception as e:
        logger.error(f"Failed to write citations: {e}")

def load_phase_state(phase_num: int) -> dict:
    """Loads an ephemeral state file, returning an empty dict if missing to prevent hard crashes."""
    path = os.path.join("cochem_setup", f"cochem_state_p{phase_num}.json")
    if not os.path.exists(path):
        print_status(f"Phase {phase_num} state missing. Using fallback defaults.", "warning")
        return {}
    with open(path, 'r') as f:
        return json.load(f)

def compile_master_registry() -> bool:
    """
    Consumes P1-P4 data, maps it to the strictly typed Pydantic Schema,
    and uses the Golden Gatekeeper to atomically write the master JSON.
    """
    print_status("Aggregating hardware, engine, and silo matrices...", "info")
    
    p1 = load_phase_state(1)
    p2 = load_phase_state(2)
    p3 = load_phase_state(3)
    p4 = load_phase_state(4)

    try:
        # Map to Pydantic Schemas (Enforces bounds, e.g., CPU >= 1)
        hardware = HardwareConfig(
            os_target=p1.get("os_info", {}).get("system", "linux_x86_64"),
            physical_cpu_cores=p2.get("physical_cpu_cores", 1),
            logical_cpu_cores=p2.get("logical_cpu_cores", 1),
            ram_gb=p2.get("ram_gb", 2.0),
            avx512_support=p2.get("avx512_support", False),
            gpu_profile=p2.get("gpu_profile", "None"),
            vram_gb=p2.get("vram_gb", 0.0),
            subnormal_precision_trap=p2.get("subnormal_precision_trap", False)
        )
        
        engines = EnginePaths(
            orca_bin=p3.get("engines", {}).get("orca", {}).get("path", "Not_Found"),
            mpirun_bin=p3.get("engines", {}).get("mpirun", {}).get("path", "Not_Found"),
            xtb_bin=p3.get("engines", {}).get("xtb", {}).get("path", "Not_Found"),
            mace_active=False # Will be validated in later workflows
        )
        
        silos = SiloConfig(
            torq_silo_active=p4.get("torq_silo_active", False),
            gpu_silo_active=p4.get("gpu_silo_active", False)
        )
        
        # Instantiate Base Routing & HPC (Will be refined by Phase 11)
        routing = RoutingPolicy()
        hpc = HPCConfig()

        master_config = CoChemConfig(
            registry_version="2026.1",
            project_root=os.path.abspath("."),
            hardware=hardware,
            engines=engines,
            silos=silos,
            routing=routing,
            hpc=hpc
        )

        # Atomic Write via Gatekeeper
        manager = RegistryManager(workspace_root=".")
        if manager.write_registry(master_config):
            print_status("Master registry atomically locked via Gatekeeper.", "success")
            return True
        return False

    except Exception as e:
        print_status(f"Schema Validation or Golden Gatekeeper Error: {e}", "fail")
        logger.error(f"Registry Compilation Exception: {e}")
        return False

def cleanup_states() -> None:
    """Purges the temporary state files to clean the workspace."""
    print_status("Performing workspace sweep of ephemeral states...", "info")
    cleaned = 0
    for i in range(1, 5):
        state_file = os.path.join("cochem_setup", f"cochem_state_p{i}.json")
        if os.path.exists(state_file):
            try:
                os.remove(state_file)
                cleaned += 1
            except OSError as e:
                logger.warning(f"Failed to remove {state_file}: {e}")
                
    print_status(f"Workspace sweep complete. Removed {cleaned} temporary files.", "success")

def main():
    print(f"\n{Colors.BOLD}--- CoChem Phase 5: Finalization & Assembly ---{Colors.ENDC}")
    write_academic_outputs()
    
    if compile_master_registry():
        cleanup_states()
        print(f"\n{Colors.BOLD}{Colors.OKGREEN}CoChem Environment Phase 1-5 successfully completed.{Colors.ENDC}")
    else:
        print(f"\n{Colors.BOLD}{Colors.FAIL}Pipeline halted during registry compilation.{Colors.ENDC}")
        sys.exit(1)

if __name__ == "__main__":
    main()