#!/usr/bin/env python3
"""
CoChem-CORE: Stage 3.0 - The Subprocess Broker
Implements: Non-blocking IPC Execution, Zombie Process Reaper,
OOM Preemption Polling, and Core-Dump Garbage Collection.
"""

import os
import time
import signal
import subprocess
import threading
import logging
from pathlib import Path
from typing import List, Optional

# Attempt psutil for OOM preemption
try:
    import psutil
    HAS_PSUTIL = True
except ImportError:
    HAS_PSUTIL = False

from cochem_core_telemetry_logger import TelemetryLogger

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger("CoChem-Broker")

class SubprocessBroker:
    def __init__(self, memory_limit_gb: float = 8.0):
        self.memory_limit_bytes = memory_limit_gb * (1024 ** 3)
        self.telemetry = TelemetryLogger()
        self.active_processes = []
        self._monitor_thread = None
        self._stop_event = threading.Event()

    def start_oom_monitor(self) -> None:
        """Background thread checking system RAM to preemptively kill before kernel panic."""
        if not HAS_PSUTIL:
            logger.warning("psutil not available. OOM Preemption disabled.")
            return

        def monitor_loop():
            while not self._stop_event.is_set():
                mem = psutil.virtual_memory()
                if mem.available < (1024 ** 3): # Less than 1GB free
                    logger.error(f"CRITICAL OOM IMMINENT. Available RAM: {mem.available / 1e6:.1f} MB")
                    self.execute_zombie_reaper()
                time.sleep(2)

        self._monitor_thread = threading.Thread(target=monitor_loop, daemon=True)
        self._monitor_thread.start()

    def stop_oom_monitor(self) -> None:
        if self._monitor_thread:
            self._stop_event.set()
            self._monitor_thread.join()

    def execute_zombie_reaper(self) -> None:
        """Hard kills all managed subprocesses and their orphaned children."""
        logger.error("Executing Zombie Reaper Protocol...")
        for proc in self.active_processes:
            try:
                # Get Process Group ID to kill children (e.g. OpenMPI threads)
                pgid = os.getpgid(proc.pid)
                os.killpg(pgid, signal.SIGKILL)
                logger.info(f"Reaped Process Group {pgid}")
            except Exception as e:
                logger.warning(f"Reaper failed on PID {proc.pid}: {e}")
        self.active_processes.clear()

    def garbage_collect_core_dumps(self, execution_dir: Path) -> None:
        """Sweeps massive binary core.* files generated by Fortran segfaults."""
        count = 0
        for file in execution_dir.glob("core.*"):
            try:
                file.unlink()
                count += 1
            except OSError:
                pass
        if count > 0:
            logger.info(f"Garbage collection swept {count} binary core dump(s).")

    def dispatch(self, job_name: str, command: List[str], execution_dir: str, env_overrides: dict = None) -> int:
        """
        Isolated dispatch loop.
        Ensures process is run in a separate group (preexec_fn=os.setsid) for clean reaping.
        """
        exec_path = Path(execution_dir)
        exec_path.mkdir(parents=True, exist_ok=True)
        
        # Strip dirty bash profile overrides
        clean_env = os.environ.copy()
        if "LD_LIBRARY_PATH" in clean_env:
            del clean_env["LD_LIBRARY_PATH"]
            
        if env_overrides:
            clean_env.update(env_overrides)

        logger.info(f"Dispatching '{job_name}' to broker...")
        
        stdout_hist = []
        stderr_hist = []
        
        try:
            # os.setsid creates a new session and process group. Critical for MPI cleanup.
            process = subprocess.Popen(
                command,
                cwd=str(exec_path),
                env=clean_env,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                preexec_fn=os.setsid 
            )
            self.active_processes.append(process)
            
            # Non-blocking read simulation (in practice, use async/select for large throughput)
            for line in iter(process.stdout.readline, ''):
                clean_line = line.strip()
                stdout_hist.append(clean_line)
                if not self.telemetry.process_stream_chunk(clean_line):
                    logger.error("Telemetry trap triggered. Preempting process.")
                    os.killpg(os.getpgid(process.pid), signal.SIGTERM)
                    break
                    
            for line in iter(process.stderr.readline, ''):
                stderr_hist.append(line.strip())
                
            process.wait()
            exit_code = process.returncode
            
        except KeyboardInterrupt:
            logger.error("Keyboard Interrupt. Triggering Reaper.")
            self.execute_zombie_reaper()
            exit_code = -1
        except Exception as e:
            logger.error(f"Dispatch Exception: {e}")
            self.execute_zombie_reaper()
            exit_code = -2
        finally:
            if process in self.active_processes:
                self.active_processes.remove(process)
            
            self.telemetry.aggregate_and_lock(job_name, stdout_hist, stderr_hist, exit_code, "DISPATCH_HASH_MOCK")
            self.garbage_collect_core_dumps(exec_path)
            
        return exit_code

if __name__ == "__main__":
    broker = SubprocessBroker()
    print("Broker Initialized and OOM protections armed.")